/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    extend: {},
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      'white': '#ffffff',
      'purple': '#3f3cbb',
      'midnight': '#121063',
      'metal': '#565584',
      'tahiti': '#3ab7bf',
      'silver': '#ecebff',
      'bubble-gum': '#ff77e9',
      'bermuda': '#78dcca',
      'black': '#0d0d0d',
      'sky' : '#004dc9',
      'white-sky': '#ecfeff',
      'gray': '#a59e92',
      'white-gray' : '#dfdcd8',
      'mid-gray': '#cdc8c1',
      'mid-black-gray': '#363636',
      'black-gray' : '#1c1c1c',
      'red': '#f14665',
      'white-blue': '#2eacef',
      'blue': '#004dc9',
      'green': '#00b140',
    },
  },
  plugins: [],
  darkMode: 'class',
};